name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-python@v6
      - name: Set env
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Build ARK
        run: |
          python _build_xbox.py
      
      - name: Upload result
        uses: actions/upload-artifact@v6
        with:
          name: RBBU-Xbox
          path: _build/xbox

  build_ps3_usa:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-python@v6
      - name: Build ARK
        run: |
          python _build_ps3.py
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-NPUB30749_00-RBBU00000"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/usa/package.conf _build/ps3
      - name: Upload result
        uses: actions/upload-artifact@v6
        with:
          name: RBBU-PS3-USA
          path: '*.pkg'

  build_ps3_eur:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-python@v6
      - name: Build ARK
        run: |
          python _build_ps3.py
      - name: Build PKG
        run: |
          Remove-Item "_build\ps3\PARAM.SFO" -Force
          Remove-Item "_build\ps3\C00\PARAM.SFO" -Force
          move "dependencies\ta_pkg_repacker_tools\eur\PARAM.SFO" "_build\ps3"
          move "dependencies\ta_pkg_repacker_tools\eur\C00\PARAM.SFO" "_build\ps3\C00"
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="EP8802-NPEB00988_00-RBBU00000"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/eur/package.conf _build/ps3
      - name: Upload result
        uses: actions/upload-artifact@v6
        with:
          name: RBBU-PS3-EUR
          path: '*.pkg'
